"""Pre-built PM templates for common industrial equipment maintenance tasks.

These are reference templates that users can apply to their machines.
Based on industry standards and manufacturer recommendations.
"""

PM_TEMPLATES = [
    {
        "id": "motor-lubrication",
        "name": "Motor Bearing Lubrication",
        "category": "lubrication",
        "description": "Grease motor bearings per manufacturer spec.",
        "trigger_type": "calendar",
        "calendar_interval_days": 90,
        "calendar_unit": "months",
        "calendar_unit_value": 3,
        "estimated_duration_minutes": 30,
        "checklist": [
            {"step": "Lock out / tag out motor", "required": True},
            {"step": "Remove grease fitting caps", "required": True},
            {"step": "Apply specified grease (2-3 pumps per fitting)", "required": True},
            {"step": "Replace caps and wipe excess", "required": True},
            {"step": "Run motor 5 min and check temperature", "required": True},
        ],
        "parts_required": [
            {"name": "Bearing Grease (NLGI #2)", "part_number": "GRS-002", "qty": 1},
        ],
        "instructions": "Use only manufacturer-approved grease. Do not over-grease — excess grease causes overheating.",
        "applicable_machine_types": ["Motor", "Pump", "Compressor", "Fan"],
    },
    {
        "id": "belt-inspection",
        "name": "Belt Tension & Wear Inspection",
        "category": "inspection",
        "description": "Inspect drive belts for tension, wear, and alignment.",
        "trigger_type": "calendar",
        "calendar_interval_days": 30,
        "calendar_unit": "months",
        "calendar_unit_value": 1,
        "estimated_duration_minutes": 20,
        "checklist": [
            {"step": "Visual inspection for cracks, fraying, glazing", "required": True},
            {"step": "Check belt tension with tension gauge", "required": True},
            {"step": "Verify pulley alignment", "required": True},
            {"step": "Record belt deflection measurement", "required": True},
        ],
        "parts_required": [],
        "instructions": "Replace belt if cracks visible or deflection exceeds 1/64 inch per inch of span.",
        "applicable_machine_types": ["Motor", "Compressor", "Conveyor", "Fan"],
    },
    {
        "id": "pump-seal-check",
        "name": "Pump Mechanical Seal Inspection",
        "category": "inspection",
        "description": "Check mechanical seals for leaks and wear.",
        "trigger_type": "calendar",
        "calendar_interval_days": 180,
        "calendar_unit": "months",
        "calendar_unit_value": 6,
        "estimated_duration_minutes": 45,
        "checklist": [
            {"step": "Check for visible leakage at seal face", "required": True},
            {"step": "Measure shaft runout", "required": True},
            {"step": "Check seal flush water flow", "required": True},
            {"step": "Record bearing temperature", "required": True},
            {"step": "Inspect coupling alignment", "required": True},
        ],
        "parts_required": [
            {"name": "Seal flush water filter", "part_number": "FLT-101", "qty": 1},
        ],
        "instructions": "If leakage exceeds 5 drops/minute, schedule seal replacement.",
        "applicable_machine_types": ["Pump"],
    },
    {
        "id": "compressor-oil-change",
        "name": "Compressor Oil Change",
        "category": "lubrication",
        "description": "Drain and replace compressor lubricant oil.",
        "trigger_type": "calendar",
        "calendar_interval_days": 365,
        "calendar_unit": "months",
        "calendar_unit_value": 12,
        "estimated_duration_minutes": 60,
        "checklist": [
            {"step": "Shut down and depressurize compressor", "required": True},
            {"step": "Drain old oil into waste container", "required": True},
            {"step": "Replace oil filter element", "required": True},
            {"step": "Fill with new oil to sight glass level", "required": True},
            {"step": "Run 10 min, check for leaks, verify oil level", "required": True},
            {"step": "Dispose of waste oil properly", "required": True},
        ],
        "parts_required": [
            {"name": "Compressor oil (5L)", "part_number": "OIL-COMP-5L", "qty": 1},
            {"name": "Oil filter element", "part_number": "FLT-OIL-200", "qty": 1},
        ],
        "instructions": "Use ISO VG 46 or manufacturer-specified oil only. Record oil sample for analysis if trending.",
        "applicable_machine_types": ["Compressor"],
    },
    {
        "id": "conveyor-roller-inspection",
        "name": "Conveyor Roller & Chain Inspection",
        "category": "inspection",
        "description": "Inspect conveyor rollers, chain tension, and alignment.",
        "trigger_type": "calendar",
        "calendar_interval_days": 14,
        "calendar_unit": "weeks",
        "calendar_unit_value": 2,
        "estimated_duration_minutes": 40,
        "checklist": [
            {"step": "Check all rollers spin freely", "required": True},
            {"step": "Listen for bearing noise on each roller", "required": True},
            {"step": "Check chain tension and adjust if needed", "required": True},
            {"step": "Inspect chain for elongation (>3% = replace)", "required": True},
            {"step": "Verify belt/chain tracking and alignment", "required": True},
            {"step": "Lubricate chain if applicable", "required": False},
        ],
        "parts_required": [
            {"name": "Chain lubricant spray", "part_number": "LUB-CHAIN-01", "qty": 1},
        ],
        "instructions": "Mark any seized rollers for replacement. Do not operate conveyor with >2 seized rollers.",
        "applicable_machine_types": ["Conveyor"],
    },
    {
        "id": "vibration-baseline",
        "name": "Vibration Baseline Recording",
        "category": "inspection",
        "description": "Record vibration baseline readings for trend analysis. Auto-handled by FactoryBrain sensors.",
        "trigger_type": "calendar",
        "calendar_interval_days": 90,
        "calendar_unit": "months",
        "calendar_unit_value": 3,
        "estimated_duration_minutes": 15,
        "checklist": [
            {"step": "Verify machine at normal operating load", "required": True},
            {"step": "Check FactoryBrain sensor dashboard for current readings", "required": True},
            {"step": "Compare with previous baseline in AI Diagnostics", "required": True},
            {"step": "Flag any reading >2x previous baseline", "required": True},
        ],
        "parts_required": [],
        "instructions": "Take readings at consistent operating conditions. FactoryBrain sensors provide continuous monitoring — this PM verifies sensor accuracy.",
        "applicable_machine_types": ["Motor", "Pump", "Compressor", "CNC", "Fan"],
    },
    {
        "id": "condition-vibration-alert",
        "name": "High Vibration Response",
        "category": "inspection",
        "description": "Triggered when vibration exceeds warning threshold. FactoryBrain auto-detects via VibeSense sensors.",
        "trigger_type": "condition",
        "condition_sensor_field": "vib_rms_x",
        "condition_operator": "gte",
        "condition_threshold": 3.5,
        "estimated_duration_minutes": 30,
        "checklist": [
            {"step": "Verify sensor reading matches actual vibration", "required": True},
            {"step": "Check mounting bolts and foundation", "required": True},
            {"step": "Check coupling alignment", "required": True},
            {"step": "Check for loose components", "required": True},
            {"step": "Record findings and recommend corrective action", "required": True},
        ],
        "parts_required": [],
        "instructions": "This PM is auto-triggered by FactoryBrain VibeSense sensors. Investigate root cause before clearing.",
        "applicable_machine_types": ["Motor", "Pump", "Compressor", "Conveyor", "CNC"],
    },
    {
        "id": "electrical-connections",
        "name": "Electrical Connection Tightness Check",
        "category": "electrical",
        "description": "Thermal scan and torque check on electrical connections.",
        "trigger_type": "calendar",
        "calendar_interval_days": 180,
        "calendar_unit": "months",
        "calendar_unit_value": 6,
        "estimated_duration_minutes": 45,
        "checklist": [
            {"step": "Perform thermal scan of all connections", "required": True},
            {"step": "Identify any hotspots (>10°C above ambient)", "required": True},
            {"step": "Re-torque terminal connections per spec", "required": True},
            {"step": "Check cable insulation condition", "required": True},
            {"step": "Verify grounding connections", "required": True},
        ],
        "parts_required": [],
        "instructions": "Requires qualified electrician. De-energize before torquing connections. Use calibrated torque wrench.",
        "applicable_machine_types": ["Motor", "Compressor", "Conveyor", "CNC", "Pump"],
    },
]


def get_template(template_id: str) -> dict | None:
    """Get a PM template by ID."""
    return next((t for t in PM_TEMPLATES if t["id"] == template_id), None)
